// export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:80';
export const API_BASE_URL = 'http://localhost:80/api';

export const venueTypes = [
  { type: 'Apartment', iconPath: '/assets/lotties/House.json' },
  { type: 'Resort', iconPath: '/assets/lotties/Resort.json' },
  { type: 'Camping', iconPath: '/assets/lotties/Camping.json' },
  { type: 'Amusement', iconPath: '/assets/lotties/RollerCoaster.json' },
];

export const venues = [
  {
    id: 1,
    name: 'Urbanite High-Rise',
    type: 'Apartment',
    rating: 4.7,
    price: '$130',
    imageUrl: '/assets/images/art1.jpg',
    description: 'Modern and chic, located in the heart of the city, close to popular attractions, restaurants, and nightlife.',
    amenities: ['Free Wi-Fi', 'Kitchen', 'Air Conditioning', 'TV', 'Washer', 'Dryer', 'Elevator', 'Parking'],
  },
  {
    id: 2,
    name: 'Sapphire Shores',
    type: 'Resort',
    rating: 5.0,
    price: '$325',
    imageUrl: '/assets/images/art2.jpg',
    description: 'A serene getaway, featuring pristine beaches and crystal-clear waters, offering a luxurious and tranquil experience.',
    amenities: ['Swimming Pool', 'Beach Access', 'Spa', 'Fitness Center', 'Restaurant', 'Bar', 'Free Wi-Fi', 'Concierge'],
  },
  {
    id: 3,
    name: 'Crestwood Camping Grounds',
    type: 'Camping',
    rating: 4.4,
    price: '$45',
    imageUrl: '/assets/images/art3.jpg',
    description: 'Nestled in a lush forest, this camping site offers a rugged yet peaceful retreat with hiking trails and wildlife spotting.',
    amenities: ['Fire Pits', 'Nature Trails', 'Picnic Tables', 'Public Restrooms', 'Guided Tours', 'Wildlife Viewing'],
  },
  {
    id: 4,
    name: 'Whimsical Wonderland',
    type: 'Amusement',
    rating: 4.5,
    price: '$80',
    imageUrl: '/assets/images/art4.jpg',
    description: 'A magical amusement park offering thrilling rides, enchanting attractions, and delicious eateries for a day full of fun.',
    amenities: ['Roller Coasters', 'Family Rides', 'Live Entertainment', 'Food Courts', 'Locker Rentals', 'First Aid Station'],
  },
  {
    id: 5,
    name: 'Lavender Luxury Loft',
    type: 'Apartment',
    rating: 4.8,
    price: '$180',
    imageUrl: '/assets/images/art3.jpg',
    description: 'A stylish loft with elegant furnishings, offering a cozy and relaxing stay with panoramic city views.',
    amenities: ['Free Wi-Fi', 'Panoramic Views', 'Smart TV', 'Fully Equipped Kitchen', 'Gym Access', 'Parking'],
  },
  // {
  //   id: 6,
  //   name: 'Pine Peak Campsite',
  //   type: 'Camping',
  //   rating: 4.2,
  //   price: '$55',
  //   imageUrl: '/assets/images/art6.jpg',
  //   description: 'A serene camping site set amidst towering pines, offering a tranquil retreat for nature lovers.',
  //   amenities: ['Picnic Tables', 'Fire Pits', 'Restrooms', 'Shower Facilities', 'Hiking Trails', 'Pet-Friendly'],
  // },
  // {
  //   id: 7,
  //   name: 'Sunnydale Holiday Resort',
  //   type: 'Resort',
  //   rating: 4.6,
  //   price: '$275',
  //   imageUrl: '/assets/images/art7.jpg',
  //   description: 'A family-friendly resort featuring spacious rooms, multiple pools, and a variety of recreational activities.',
  //   amenities: ['Multiple Pools', 'Kids Club', 'All-Inclusive Option', 'Entertainment', 'Fitness Center', 'Free Wi-Fi'],
  // },
  // {
  //   id: 8,
  //   name: 'Aqua Adventure Water Park',
  //   type: 'Amusement',
  //   rating: 4.3,
  //   price: '$90',
  //   imageUrl: '/assets/images/art8.jpg',
  //   description: 'A splash-tastic water park featuring a variety of water rides, wave pools, and relaxation areas for a fun-filled day.',
  //   amenities: ['Various Water Rides', 'Wave Pools', 'Food Courts', 'Locker Rentals', 'First Aid Station', 'Parking'],
  // },
  // {
  //   id: 9,
  //   name: 'Metropolitan Mansion Apartments',
  //   type: 'Apartment',
  //   rating: 4.7,
  //   price: '$160',
  //   imageUrl: '/assets/images/art9.jpg',
  //   description: 'Luxurious apartments located in a bustling metropolis, featuring top-notch amenities and proximity to entertainment hubs.',
  //   amenities: ['Luxury Furnishings', 'High-Speed Wi-Fi', 'Fitness Center', 'Parking', '24/7 Security', 'Pet-Friendly'],
  // },
  // {
  //   id: 10,
  //   name: 'Forest Haven Camping',
  //   type: 'Camping',
  //   rating: 4.5,
  //   price: '$50',
  //   imageUrl: '/assets/images/art10.jpg',
  //   description: 'A beautiful camping site surrounded by dense foliage, offering solitude and a host of outdoor activities.',
  //   amenities: ['Fire Pit', 'Nature Trails', 'Picnic Area', 'Wildlife Viewing', 'Restrooms', 'Camping Essentials'],
  // },
  // {
  //   id: 11,
  //   name: 'Tropical Bliss Resort',
  //   type: 'Resort',
  //   rating: 4.9,
  //   price: '$350',
  //   imageUrl: '/assets/images/art11.jpg',
  //   description: 'An exquisite resort located on a secluded island, featuring private beaches, spa services, and gourmet dining.',
  //   amenities: ['Private Beach', 'Spa Services', 'Fine Dining', 'Water Sports', 'Fitness Center', 'Free Wi-Fi'],
  // },
  // {
  //   id: 12,
  //   name: 'Skyline Amusement Park',
  //   type: 'Amusement',
  //   rating: 4.4,
  //   price: '$95',
  //   imageUrl: '/assets/images/art12.jpg',
  //   description: 'A dynamic amusement park with roller coasters, live shows, and interactive attractions for an exhilarating experience.',
  //   amenities: ['Roller Coasters', 'Live Shows', 'Food Stalls', 'ATMs', 'First Aid', 'Lost & Found'],
  // }
];
